services:
  musicapp:
    container_name: musicapp
    image: musicapp
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      DATABASE_URL: "host=musicapp-db user=root password=root dbname=musicapp sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - musicapp-db
      - pgadmin
  musicapp-db:
    container_name: musicapp-db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: musicapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdata: {}
  pgadmin: {}
